#!/bin/bash

while :
do
	# Check if the Regata OS Game Access is running
	ps -C "regataosgcs" > /dev/null
	if [ $? = 0 ]
	then
		# Capture progress for JavaScript
		if test -e /tmp/progressbar-gcs/download-percentage ; then
			lines=$(wc -l /tmp/progressbar-gcs/download-percentage | cut -d"/" -f -1)
			if [ $lines -ge 10 ]; then
				# Progress bar and percentage
				progress=$(tail -2 /tmp/progressbar-gcs/download-percentage | awk '{print $7}' | head -1 | tail -1)

				if [[ $progress == *"salvo"* ]]; then
					echo "100%"
				elif [[ $progress == *"saved"* ]]; then
					echo "100%"
				else
					echo $progress > /tmp/progressbar-gcs/progress
				fi

				# Internet connection speed and estimated time of conclusion
				check_progress=$(grep -r 100% /tmp/progressbar-gcs/download-percentage)

				if [[ $check_progress == *"100%"* ]]; then
					rm -f "/tmp/progressbar-gcs/speed"
					rm -f "/tmp/progressbar-gcs/eta"
				else
					speed=$(tail -2 /tmp/progressbar-gcs/download-percentage | awk '{print $8}' | head -1 | tail -1 | sed 's,M, MB/s,' | sed 's,K, KB/s,' | sed 's,G, GB/s,')
					echo $speed > /tmp/progressbar-gcs/speed
					eta=$(tail -2 /tmp/progressbar-gcs/download-percentage | awk '{print $9}' | head -1 | tail -1 | sed 's/h/h /' | sed 's/m/m /' | sed 's/s/s /')
					echo $eta > /tmp/progressbar-gcs/eta
				fi

				# Download Size
				download_size=$(grep -r application /tmp/progressbar-gcs/download-percentage | tail -1 | head -1 | awk '{print $3}' | sed 's/(\|)//g' | sed 's/M/ MB/' | sed 's/K/ KB/' | sed 's/G/ GB/')
				download_size2=$(grep -r application /tmp/progressbar-gcs/download-percentage | tail -1 | head -1 | awk '{print $3}' | sed 's/(\|)//g' | sed 's/M//' | sed 's/K//' | sed 's/G//')
				echo "$download_size" > /tmp/progressbar-gcs/download-size

				# Downloading File Size
				file_downloading=$(cat /tmp/progressbar-gcs/file-download-size)
				file_size=$(du -hs $file_downloading | awk '{print $1}' | sed 's/M/ MB/' | sed 's/K/ KB/' | sed 's/G/ GB/')
				file_size2=$(du -hs $file_downloading | awk '{print $1}' | sed 's/M//' | sed 's/K//' | sed 's/G//')
				
				if [ $file_size2 -ge $download_size2 ]; then
					echo "$download_size /" > /tmp/progressbar-gcs/file-size
				else
					echo "$file_size /" > /tmp/progressbar-gcs/file-size
				fi

				# Get Wget PID
				get_pid=$(cat /tmp/progressbar-gcs/get-pid)
				pid=$(ps -C "$get_pid" | awk '{print $1}'| tail -1)
				echo $pid > /tmp/progressbar-gcs/wget-pid
			fi

		elif test -e "/tmp/progressbar-gcs/download-percentage-legendary"; then
			lines=$(wc -l /tmp/progressbar-gcs/download-percentage-legendary | cut -d"/" -f -1)
			if [ $lines -ge 12 ]; then
				# Progress bar and percentage
				progress=$(cat /tmp/progressbar-gcs/download-percentage-legendary | grep "Progress" | awk '{print $5}' | tail -1 | head -1 | cut -d"." -f -1)

				if [[ $progress == *"100.00%"* ]]; then
					echo "100%"
				else
					echo "$progress%" > /tmp/progressbar-gcs/progress
				fi

				# Internet connection speed and estimated time of conclusion
				check_progress=$(cat /tmp/progressbar-gcs/download-percentage-legendary | grep "Progress" | awk '{print $5}' | tail -1 | head -1 | cut -d"." -f -1)

				if [[ $check_progress == *"100.00%"* ]]; then
					rm -f "/tmp/progressbar-gcs/speed"
					rm -f "/tmp/progressbar-gcs/eta"
				else
					speed=$(cat /tmp/progressbar-gcs/download-percentage-legendary | grep "Download" | awk '{print $6 $7}' | tail -1 | head -1 | sed 's/K/ K/' | sed 's/M/ M/' | sed 's/G/ G/')
					echo $speed > /tmp/progressbar-gcs/speed
					eta=$(cat /tmp/progressbar-gcs/download-percentage-legendary | grep "ETA" | awk '{print $11}' | tail -1 | head -1)
					echo "$(echo $eta)h" > /tmp/progressbar-gcs/eta
				fi

				# Download Size
				game_size=$(cat /tmp/progressbar-gcs/download-percentage-legendary | grep "Download size" | awk '{print $5}' | tail -1 | head -1 | cut -d"." -f -1)

				if [[ $game_size =~ $(echo "^[0-9]+$") ]]; then
					download_size_bytes=$(( $game_size * 1024*1024 ))
				fi

				echo "$download_size_bytes" > /tmp/progressbar-gcs/download-size-bytes

				# Downloading File Size
				download_percentage=$(cat /tmp/progressbar-gcs/download-percentage-legendary | grep "Downloaded" | awk '{print $5}' | tail -1 | head -1 | sed 's/,//g' | cut -d"." -f -1)

				if [[ $download_percentage =~ $(echo "^[0-9]+$") ]]; then
					file_size_bytes=$(( $download_percentage * 1024*1024 ))
				fi

				echo "$file_size_bytes" > /tmp/progressbar-gcs/file-size-bytes
			fi
		else
			echo "Nothing to do..."
		fi

	else
		echo "Nothing to do..."
		break
	fi

   sleep 1
done
