#!/bin/bash

cd /

while :
do

# Check if the Regata OS Game Access is running
ps -C "regataosgcs" > /dev/null
if [ $? = 0 ]
then
	progressbar_dir="/tmp/progressbar-gcs"

	#Make sure there are no critical installation errors
	if test -e "$progressbar_dir/abort-installations" ; then
		# Abort installations
		rm -f $progressbar_dir/*
	else

		# Check process queue and sort by sequence
		if test -e "$progressbar_dir/queued-process" ; then
			check_lines=$(grep -c p $progressbar_dir/queued-process)

			if [ $check_lines -ge 1 ]; then
				queued1=$(cat $progressbar_dir/queued-process | head -1 | tail -1 | cut -d"=" -f 2- | cut -d"-" -f 2-)
				echo $queued1 > $progressbar_dir/queued-1
			else
				rm -f "$progressbar_dir/queued-1"
			fi

			if [ $check_lines -ge 2 ]; then
				queued2=$(cat $progressbar_dir/queued-process | head -2 | tail -1 | cut -d"=" -f 2- | cut -d"-" -f 2-)
				echo $queued2 > $progressbar_dir/queued-2
			else
				rm -f "$progressbar_dir/queued-2"
			fi

			if [ $check_lines -ge 3 ]; then
				queued3=$(cat $progressbar_dir/queued-process | head -3 | tail -1 | cut -d"=" -f 2- | cut -d"-" -f 2-)
				echo $queued3 > $progressbar_dir/queued-3
			else
				rm -f "$progressbar_dir/queued-3"
			fi

			if [ $check_lines -ge 4 ]; then
				queued4=$(cat $progressbar_dir/queued-process | head -4 | tail -1 | cut -d"=" -f 2- | cut -d"-" -f 2-)
				echo $queued4 > $progressbar_dir/queued-4
			else
				rm -f "$progressbar_dir/queued-4"
			fi

			if [ $check_lines -ge 5 ]; then
				queued5=$(cat $progressbar_dir/queued-process | head -5 | tail -1 | cut -d"=" -f 2- | cut -d"-" -f 2-)
				echo $queued5 > $progressbar_dir/queued-5
			else
				rm -f "$progressbar_dir/queued-5"
			fi

			if [ $check_lines -ge 6 ]; then
				queued6=$(cat $progressbar_dir/queued-process | head -6 | tail -1 | cut -d"=" -f 2- | cut -d"-" -f 2-)
				echo $queued6 > $progressbar_dir/queued-6
			else
				rm -f "$progressbar_dir/queued-6"
			fi

			if [ $check_lines -ge 7 ]; then
				queued7=$(cat $progressbar_dir/queued-process | head -7 | tail -1 | cut -d"=" -f 2- | cut -d"-" -f 2-)
				echo $queued7 > $progressbar_dir/queued-7
			else
				rm -f "$progressbar_dir/queued-7"
			fi

			if [ $check_lines -ge 8 ]; then
				queued8=$(cat $progressbar_dir/queued-process | head -8 | tail -1 | cut -d"=" -f 2- | cut -d"-" -f 2-)
				echo $queued8 > $progressbar_dir/queued-8
			else
				rm -f "$progressbar_dir/queued-8"
			fi

		else
			rm -f "$progressbar_dir/queued-1"
			rm -f "$progressbar_dir/queued-2"
			rm -f "$progressbar_dir/queued-3"
			rm -f "$progressbar_dir/queued-4"
			rm -f "$progressbar_dir/queued-5"
			rm -f "$progressbar_dir/queued-6"
			rm -f "$progressbar_dir/queued-7"
			rm -f "$progressbar_dir/queued-8"
		fi
	fi

else
	echo "Nothing to do..."
	break
fi

   sleep 1
done
