#!/bin/bash

# Run installed game and display icon in system taskbar
export GAME="ts4";
export LAUNCHER="origin";
export RUNGAME="origin://LaunchGame/OFB-EAST:109552299";

/opt/regataos-gcs/scripts/action-games/rungame start
