#!/bin/bash
#

# Settings and variables
# General information
game_nickname="$2"
app_name="$(grep -r "gamename" /opt/regataos-gcs/games-list/$game_nickname.json | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g')"
conf_prefix_status="Preparando o modo de compatibilidade..."
success_installation="Concluído"
progressbar_dir="/tmp/progressbar-gcs"

# If Vulkan is supported, enable DXVK and VKD3D-Proton
function enable_dxvk_vkd3d() {
	export WINEPREFIX="$HOME/.local/share/wineprefixes/default-compatibility-mode"
	/bin/bash /opt/regataos-gcs/scripts/action-games/configure-compatibility-mode -configure-dxvk-vkd3d
}

function prepareCustomCompatMode() {
	if test -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode/system.reg"; then
		# We're finished!
		exit 0

	else
		# Configuring compatibility mode
		echo "installing" >$progressbar_dir/progress-movement
		echo "" >$progressbar_dir/progress
		echo $app_name >$progressbar_dir/app-name
		echo $conf_prefix_status >$progressbar_dir/status
		sleep 1
		echo "show progress bar" >$progressbar_dir/progressbar

		export WINEPREFIX="$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"

		# Variables for custom Wine
		export CUSTOM_WINE_DIR="$(cat $HOME/.config/regataos-gcs/custom-runtime/$game_nickname.txt)"

		export WINEDLLPATH="$CUSTOM_WINE_DIR/lib:$CUSTOM_WINE_DIR/lib64"
		export WINESERVER="$CUSTOM_WINE_DIR/bin/wineserver"
		export WINELOADER="$CUSTOM_WINE_DIR/bin/wine"
		export WINE="$CUSTOM_WINE_DIR/bin/wine"

		alias wine="$CUSTOM_WINE_DIR/bin/wine"
		alias wine64="$CUSTOM_WINE_DIR/bin/wine64"
		alias wineserver="$CUSTOM_WINE_DIR/bin/wineserver"
		alias wineboot="$CUSTOM_WINE_DIR/bin/wineboot"
		alias winecfg="$CUSTOM_WINE_DIR/bin/winecfg"
		alias msiexec="$CUSTOM_WINE_DIR/bin/msiexec"

		$CUSTOM_WINE_DIR/bin/wine $CUSTOM_WINE_DIR/bin/wineboot

		# Apply DLL settings 
		overrideDll() {
			$CUSTOM_WINE_DIR/bin/wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v $1 /d native /f >/dev/null 2>&1
		}

		# Install DXVK and VKD3D-Proton dll's
		#DXVK
		for dll in $(ls /opt/regataos-wine/dxvk/x64/ | grep "dll"); do
			ln -sf "/opt/regataos-wine/dxvk/x64/$dll" "$WINEPREFIX/drive_c/windows/system32/$dll"

			overrideDll $(echo "$dll" | sed s/.dll//)
		done

		for dll in $(ls /opt/regataos-wine/dxvk/x32/ | grep "dll"); do
			ln -sf "/opt/regataos-wine/dxvk/x32/$dll" "$WINEPREFIX/drive_c/windows/syswow64/$dll"

			overrideDll $(echo "$dll" | sed s/.dll//)
		done

		#VKD3D-Proton
		for dll in $(ls /opt/regataos-wine/vkd3d-proton/x64/ | grep "dll"); do
			ln -sf "/opt/regataos-wine/vkd3d-proton/x64/$dll" "$WINEPREFIX/drive_c/windows/system32/$dll"

			overrideDll $(echo "$dll" | sed s/.dll//)
		done

		for dll in $(ls /opt/regataos-wine/vkd3d-proton/x86/ | grep "dll"); do
			ln -sf "/opt/regataos-wine/vkd3d-proton/x86/$dll" "$WINEPREFIX/drive_c/windows/syswow64/$dll"

			overrideDll $(echo "$dll" | sed s/.dll//)
		done

		echo -e "DXVK\nVKD3D-Proton" >>"$WINEPREFIX/vulkan.txt"

		# Check the winetricks cache present on the system.
		if test ! -e "$HOME/.cache/winetricks/vcrun2019"; then
			if test -e "/opt/regataos-wine/winetricks-cache/winetricks.tar.xz"; then
				mkdir -p "$HOME/.cache"
				tar xf "/opt/regataos-wine/winetricks-cache/winetricks.tar.xz" -C "$HOME/.cache/"
			fi
		fi

		winetricks-gcs prefix=$game_nickname-compatibility-mode -q -f win10
		sleep 5

		rm -f $progressbar_dir/progress-movement
		echo "completed" >$progressbar_dir/progress-full
		echo "" >$progressbar_dir/status
		echo $success_installation >$progressbar_dir/progress
		sleep 2
	fi
}

function prepareDefaultCompatMode() {
	if test -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode/system.reg"; then
		# We're finished!
		exit 0

	elif test -e "$HOME/.local/share/wineprefixes/default-compatibility-mode/system.reg"; then
		# Configuring compatibility mode
		echo "installing" >$progressbar_dir/progress-movement
		echo "" >$progressbar_dir/progress
		echo $app_name >$progressbar_dir/app-name
		echo $conf_prefix_status >$progressbar_dir/status
		sleep 1
		echo "show progress bar" >$progressbar_dir/progressbar

		# Enable DXVK and VKD3D-Proton
		if test ! -e "$HOME/.local/share/wineprefixes/default-compatibility-mode/vulkan.txt"; then
			enable_dxvk_vkd3d
		fi

		mkdir -p "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"
		cp -rf $HOME/.local/share/wineprefixes/default-compatibility-mode/* \
			"$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode/"
		sleep 5

		rm -f $progressbar_dir/progress-movement
		echo "completed" >$progressbar_dir/progress-full
		echo "" >$progressbar_dir/status
		echo $success_installation >$progressbar_dir/progress
		sleep 2

	else
		# Configuring compatibility mode
		echo "installing" >$progressbar_dir/progress-movement
		echo "" >$progressbar_dir/progress
		echo $app_name >$progressbar_dir/app-name
		echo $conf_prefix_status >$progressbar_dir/status
		sleep 1
		echo "show progress bar" >$progressbar_dir/progressbar

		# Check the winetricks cache present on the system.
		if test ! -e "$HOME/.cache/winetricks/vcrun2019"; then
			if test -e "/opt/regataos-wine/winetricks-cache/winetricks.tar.xz"; then
				mkdir -p "$HOME/.cache"
				tar xf "/opt/regataos-wine/winetricks-cache/winetricks.tar.xz" -C "$HOME/.cache/"
			fi
		fi

		mkdir -p "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"
		export WINEPREFIX="$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"

		winetricks-gcs prefix=$game_nickname-compatibility-mode -q -f nocrashdialog
		winetricks-gcs prefix=$game_nickname-compatibility-mode -q -f d3dcompiler_43
		winetricks-gcs prefix=$game_nickname-compatibility-mode -q -f d3dx9

		# Apply DLL settings 
		overrideDll() {
			$CUSTOM_WINE_DIR/bin/wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v $1 /d native /f >/dev/null 2>&1
		}

		# Install d3dcompiler_47 dll
		for dll in $(ls /opt/regataos-wine/dlls/default/x64/ | grep "dll"); do
			cp -f "/opt/regataos-wine/dlls/default/x64/$dll" "$WINEPREFIX/drive_c/windows/system32/$dll"

			overrideDll $(echo "$dll" | sed s/.dll//)
		done

		for dll in $(ls /opt/regataos-wine/dlls/default/x32/ | grep "dll"); do
			cp -f "/opt/regataos-wine/dlls/default/x32/$dll" "$WINEPREFIX/drive_c/windows/syswow64/$dll"

			overrideDll $(echo "$dll" | sed s/.dll//)
		done

		# Install DXVK and VKD3D-Proton dll's
		#DXVK
		for dll in $(ls /opt/regataos-wine/dxvk/x64/ | grep "dll"); do
			ln -sf "/opt/regataos-wine/dxvk/x64/$dll" "$WINEPREFIX/drive_c/windows/system32/$dll"

			overrideDll $(echo "$dll" | sed s/.dll//)
		done

		for dll in $(ls /opt/regataos-wine/dxvk/x32/ | grep "dll"); do
			ln -sf "/opt/regataos-wine/dxvk/x32/$dll" "$WINEPREFIX/drive_c/windows/syswow64/$dll"

			overrideDll $(echo "$dll" | sed s/.dll//)
		done

		#VKD3D-Proton
		for dll in $(ls /opt/regataos-wine/vkd3d-proton/x64/ | grep "dll"); do
			ln -sf "/opt/regataos-wine/vkd3d-proton/x64/$dll" "$WINEPREFIX/drive_c/windows/system32/$dll"

			overrideDll $(echo "$dll" | sed s/.dll//)
		done

		for dll in $(ls /opt/regataos-wine/vkd3d-proton/x86/ | grep "dll"); do
			ln -sf "/opt/regataos-wine/vkd3d-proton/x86/$dll" "$WINEPREFIX/drive_c/windows/syswow64/$dll"

			overrideDll $(echo "$dll" | sed s/.dll//)
		done

		echo -e "DXVK\nVKD3D-Proton" >>"$WINEPREFIX/vulkan.txt"

		winetricks-gcs prefix=$game_nickname-compatibility-mode -q -f win10
		sleep 5

		rm -f $progressbar_dir/progress-movement
		echo "completed" >$progressbar_dir/progress-full
		echo "" >$progressbar_dir/status
		echo $success_installation >$progressbar_dir/progress
		sleep 2
	fi
}

case $1 in
"-dcm")
	prepareDefaultCompatMode
	;;
"-lcm")
	prepareCustomCompatMode
	;;
*)
	echo "Invalid option!"
	exit 1
	;;
esac
