#!/bin/bash 
#

# Settings and variables
# General information
game_nickname="$2"
app_name="$(grep -r "gamename" /opt/regataos-gcs/games-list/$game_nickname.json | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g')"
conf_prefix_status="Preparing compatibility mode..."
success_installation="Concluded"
progressbar_dir="/tmp/progressbar-gcs"

# If Vulkan is supported, enable DXVK and VKD3D-Proton
function enable_dxvk_vkd3d() {
	export WINEPREFIX="$HOME/.local/share/wineprefixes/default-compatibility-mode"
	/bin/bash /opt/regataos-gcs/scripts/action-games/configure-compatibility-mode -configure-dxvk-vkd3d
}

function prepareCustomCompatMode() {
	if test -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"; then
		# We're finished!
		exit 0

	else
		# Configuring compatibility mode
		echo "installing" > $progressbar_dir/progress-movement
		echo "" > $progressbar_dir/progress
		echo $app_name > $progressbar_dir/app-name
		echo $conf_prefix_status > $progressbar_dir/status
		sleep 1
		echo "show progress bar" > $progressbar_dir/progressbar

		export WINEDLLOVERRIDES="mscoree,mshtml="
		export WINEPREFIX="$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"

		# Variables for custom Wine
		export CUSTOM_WINE_DIR="$(cat $HOME/.config/regataos-gcs/custom-runtime/$game_nickname.txt)"

		export WINEDLLPATH="$CUSTOM_WINE_DIR/lib:$CUSTOM_WINE_DIR/lib64"
		export WINESERVER="$CUSTOM_WINE_DIR/bin/wineserver"
		export WINELOADER="$CUSTOM_WINE_DIR/bin/wine"
		export WINE="$CUSTOM_WINE_DIR/bin/wine"

		alias wine="$CUSTOM_WINE_DIR/bin/wine"
		alias wine64="$CUSTOM_WINE_DIR/bin/wine64"
		alias wineserver="$CUSTOM_WINE_DIR/bin/wineserver"
		alias wineboot="$CUSTOM_WINE_DIR/bin/wineboot"
		alias winecfg="$CUSTOM_WINE_DIR/bin/winecfg"
		alias msiexec="$CUSTOM_WINE_DIR/bin/msiexec"

		winetricks prefix=$game_nickname-compatibility-mode -q -f nocrashdialog
		winetricks prefix=$game_nickname-compatibility-mode -q -f d3dcompiler_43
		winetricks prefix=$game_nickname-compatibility-mode -q -f d3dx9

		# Install d3dcompiler_47 dll
		overrideDll() {
			wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v $1 /d native /f >/dev/null 2>&1
		}

		for dll in $(ls /opt/regataos-wine/dlls/default/x64/ | grep "dll"); do
			cp -f "/opt/regataos-wine/dlls/default/x64/$dll" "$WINEPREFIX/drive_c/windows/system32/$dll"

			overrideDll $(echo "$dll" | sed s/.dll//)
		done

		for dll in $(ls /opt/regataos-wine/dlls/default/x32/ | grep "dll"); do
			cp -f "/opt/regataos-wine/dlls/default/x32/$dll" "$WINEPREFIX/drive_c/windows/syswow64/$dll"

			overrideDll $(echo "$dll" | sed s/.dll//)
		done

		# Check the winetricks cache present on the system.
		if test ! -e "$HOME/.cache/winetricks/vcrun2019"; then
			if test -e "/opt/regataos-wine/winetricks-cache/winetricks.tar.xz"; then
				mkdir -p "$HOME/.cache"
				tar xf "/opt/regataos-wine/winetricks-cache/winetricks.tar.xz" -C "$HOME/.cache/"
			fi
		fi

		winetricks prefix=$game_nickname-compatibility-mode -q -f win10
		sleep 5

		# Enable DXVK and VKD3D-Proton
		/bin/bash /opt/regataos-gcs/scripts/action-games/configure-compatibility-mode -configure-dxvk-vkd3d

		rm -f $progressbar_dir/progress-movement
		echo "completed" > $progressbar_dir/progress-full
		echo "" > $progressbar_dir/status
		echo $success_installation > $progressbar_dir/progress
		sleep 2
		rm -f $progressbar_dir/*
	fi
}

function prepareDefaultCompatMode() {
	if test -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode" ; then
		# We're finished!
		exit 0

	elif test -e "$HOME/.local/share/wineprefixes/default-compatibility-mode" ; then
		if test ! -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode" ; then
			# Configuring compatibility mode
			echo "installing" > $progressbar_dir/progress-movement
			echo "" > $progressbar_dir/progress
			echo $app_name > $progressbar_dir/app-name
			echo $conf_prefix_status > $progressbar_dir/status
			sleep 1
			echo "show progress bar" > $progressbar_dir/progressbar

			# Enable DXVK and VKD3D-Proton
			if test ! -e "$HOME/.local/share/wineprefixes/default-compatibility-mode/vulkan.txt"; then
				enable_dxvk_vkd3d
			fi

			cp -rf "$HOME/.local/share/wineprefixes/default-compatibility-mode" \
			"$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"

			rm -f $progressbar_dir/progress-movement
			echo "completed" > $progressbar_dir/progress-full
			echo "" > $progressbar_dir/status
			echo $success_installation > $progressbar_dir/progress
			sleep 2
			rm -f $progressbar_dir/*
		else
			# We're finished!
			exit 0
		fi

	elif test -e "/usr/share/regataos/compatibility-mode/default-wineprefix.tar.xz" ; then
		if test ! -e "$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode" ; then
			# Configuring compatibility mode
			echo "installing" > $progressbar_dir/progress-movement
			echo "" > $progressbar_dir/progress
			echo $app_name > $progressbar_dir/app-name
			echo $conf_prefix_status > $progressbar_dir/status
			sleep 1
			echo "show progress bar" > $progressbar_dir/progressbar

			if test -e "/usr/share/regataos/compatibility-mode/default-wineprefix.tar.xz" ; then
				tar xf "/usr/share/regataos/compatibility-mode/default-wineprefix.tar.xz" -C "$HOME/.local/share/wineprefixes/"
			fi

			# Enable DXVK and VKD3D-Proton
			if test ! -e "$HOME/.local/share/wineprefixes/default-compatibility-mode/vulkan.txt"; then
				enable_dxvk_vkd3d
			fi

			cp -rf "$HOME/.local/share/wineprefixes/default-compatibility-mode" \
			"$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"

			rm -f $progressbar_dir/progress-movement
			echo "completed" > $progressbar_dir/progress-full
			echo "" > $progressbar_dir/status
			echo $success_installation > $progressbar_dir/progress
			sleep 2
			rm -f $progressbar_dir/*
		fi

		# We're finished!
		exit 0

	else
		# Configuring compatibility mode
		echo "installing" > $progressbar_dir/progress-movement
		echo "" > $progressbar_dir/progress
		echo $app_name > $progressbar_dir/app-name
		echo $conf_prefix_status > $progressbar_dir/status
		sleep 1
		echo "show progress bar" > $progressbar_dir/progressbar

		/opt/regataos-gcs/scripts/prepare-default-compatibility-mode.sh start

		# Enable DXVK and VKD3D-Proton
		if test ! -e "$HOME/.local/share/wineprefixes/default-compatibility-mode/vulkan.txt"; then
			enable_dxvk_vkd3d
		fi

		cp -rf "$HOME/.local/share/wineprefixes/default-compatibility-mode" \
		"$HOME/.local/share/wineprefixes/$game_nickname-compatibility-mode"

		rm -f $progressbar_dir/progress-movement
		echo "completed" > $progressbar_dir/progress-full
		echo "" > $progressbar_dir/status
		echo $success_installation > $progressbar_dir/progress
		sleep 2
		rm -f $progressbar_dir/*
	fi
}

case $1 in
   "-dcm") prepareDefaultCompatMode
         ;;
   "-lcm") prepareCustomCompatMode
         ;;
   *) echo "Invalid option!"
      exit 1
      ;;
esac
