#!/bin/bash

# This script ends the application of the Regata OS Game Access application
# when a game or launcher was executed from it

cd /

while :
do

# Make sure the Game Access app auto-close option is enabled
if [[ $(grep -r "auto-close=" $HOME/.config/regataos-gcs/regataos-gcs.conf | cut -d"=" -f 2-) == *"true"* ]]; then
	# Check if the Regata OS Game Access is running
	ps -C "regataosgcs /opt/regataos-gcs" > /dev/null
	if [ $? = 0 ]
	then
		# Check if any game or launcher has been run from the game access
		if test -e "/tmp/regataos-gcs/running-with-regataos-gcs.txt" ; then
			# When this file is removed, the scan restarts
			if test -e "/tmp/regataos-gcs/run-regataos-gcs.txt"; then
				rm -f "/tmp/regataos-gcs/run-regataos-gcs.txt"
			fi

			# If Game Access is running, close the application
			ps -C "regataosgcs /opt/regataos-gcs" > /dev/null
			if [ $? = 0 ]; then
				echo "Close the Game Access application"
				kill -SIGTERM $(ps -C regataosgcs | head -2 | tail -1 | awk '{print $1}')
				sleep 5
				sed -i 's/\(closed-manually=true\)/closed-manually=false/' "$HOME/.config/regataos-gcs/regataos-gcs.conf"

			else
				# Verify that process is running
				if [[ $(ps axu | grep "regataos-wine/wine" | sed "/grep/d") == *"regataos-wine/wine"* ]]; then
					echo "" > "/tmp/regataos-gcs/run-regataos-gcs.txt"

				else
					ps -C "rungame-steam" > /dev/null
					if [ $? = 0 ]; then
						echo "" > "/tmp/regataos-gcs/run-regataos-gcs.txt"
					fi
				fi

				# If the launcher or game is closed, start Game Access
				if test ! -e "/tmp/regataos-gcs/run-regataos-gcs.txt"; then
					if [[ $(grep -r "closed-manually=" $HOME/.config/regataos-gcs/regataos-gcs.conf | cut -d"=" -f 2-) != *"true"* ]]; then
						sed -i 's/\(closed-manually=true\)/closed-manually=false/' "$HOME/.config/regataos-gcs/regataos-gcs.conf"

						rm -f "/tmp/regataos-gcs/running-with-regataos-gcs.txt"
						cd "/usr/share/applications/"
						gtk-launch "regataos-gcs.desktop"
					fi
				fi
			fi
		fi

	else
		# Check if any game or launcher has been run from the game access
		if test -e "/tmp/regataos-gcs/running-with-regataos-gcs.txt" ; then
			# When this file is removed, the scan restarts
			if test -e "/tmp/regataos-gcs/run-regataos-gcs.txt"; then
				rm -f "/tmp/regataos-gcs/run-regataos-gcs.txt"
			fi

			# If Game Access is running, close the application
			ps -C "regataosgcs /opt/regataos-gcs" > /dev/null
			if [ $? = 0 ]; then
				echo "Close the Game Access application"
				kill -SIGTERM $(ps -C regataosgcs | head -2 | tail -1 | awk '{print $1}')
				sleep 5
				sed -i 's/\(closed-manually=true\)/closed-manually=false/' "$HOME/.config/regataos-gcs/regataos-gcs.conf"

			else
				# Verify that process is running
				if [[ $(ps axu | grep "regataos-wine/wine" | sed "/grep/d") == *"regataos-wine/wine"* ]]; then
					echo "" > "/tmp/regataos-gcs/run-regataos-gcs.txt"

				else
					ps -C "rungame-steam" > /dev/null
					if [ $? = 0 ]; then
						echo "" > "/tmp/regataos-gcs/run-regataos-gcs.txt"
					fi
				fi

				# If the launcher or game is closed, start Game Access
				if test ! -e "/tmp/regataos-gcs/run-regataos-gcs.txt"; then
					if [[ $(grep -r "closed-manually=" $HOME/.config/regataos-gcs/regataos-gcs.conf | cut -d"=" -f 2-) != *"true"* ]]; then
						sed -i 's/\(closed-manually=true\)/closed-manually=false/' "$HOME/.config/regataos-gcs/regataos-gcs.conf"

						rm -f "/tmp/regataos-gcs/running-with-regataos-gcs.txt"
						cd "/usr/share/applications/"
						gtk-launch "regataos-gcs.desktop"
					fi
				fi
			fi

		else
			echo "Nothing to do..."
			break
		fi
	fi

else
	ps -C "regataosgcs /opt/regataos-gcs" > /dev/null
	if [ $? = 1 ]
	then
		echo "Nothing to do..."
		break
	else
		echo "Nothing to do..."
	fi
fi

   sleep 5
done
