#!/bin/sh

# Update wineprefix username
function update_wineprefix_username() {
    user=$(users | awk '{print $1}')

    if test ! -e "$WINEPREFIX/drive_c/users/$user"; then
        # Update files with username
        mv -f "$WINEPREFIX/drive_c/users/marcos" "$WINEPREFIX/drive_c/users/$user"

        update_username=(
            system.reg
            user.reg
            userdef.reg
        )

        for files in "${update_username[@]}"; do
            sed -i "s/marcos/$user/g" "$WINEPREFIX/drive_c/users/$user/$files"
        done

        # Create symbolic links to user folders
        create_symbolic_links=(
            Documents
            Downloads
            Music
            Pictures
            Videos
        )

        for link in "${create_symbolic_links[@]}"; do
            rm -f "$WINEPREFIX/drive_c/users/$user/$link"

            ln -sf "$(cat $HOME/.config/user-dirs.dirs | grep -i $link | cut -d"=" -f 2- | sed 's/"//g' | sed 's|$HOME|'/home/$user'|')" \
                "$WINEPREFIX/drive_c/users/$user/$link"
        done

        rm -f "$WINEPREFIX/drive_c/users/$user/Desktop"
        ln -sf "$HOME/.local/share/applications" "$WINEPREFIX/drive_c/users/$user/Desktop"

    else
        rm -f "$WINEPREFIX/drive_c/users/$user/Desktop"
        ln -sf "$HOME/.local/share/applications" "$WINEPREFIX/drive_c/users/$user/Desktop"
    fi
}

# If Vulkan is supported, enable DXVK and VKD3D-Proton.
function configure_dxvk_vkd3d() {
    if [ -z $WINEPREFIX ]; then
        echo 'The "$WINEPREFIX" environment variable is empty. Going out...'
        exit 1
    fi

    update_wineprefix_username

    if test ! -e "$WINEPREFIX/vulkan.txt"; then
        vulkan_test=$(vulkaninfo)
        if [[ $vulkan_test == *"Instance Extensions"* ]]; then
            if [[ $vulkan_test != *"Vulkan support is incomplete"* ]]; then
                # Function to set DLLs as native by default
                overrideDll() {
                    export WINEDLLOVERRIDES="mscoree,mshtml="
                    export WINEPREFIX=$(echo "$WINEPREFIX")

                    wine reg add 'HKEY_CURRENT_USER\Software\Wine\DllOverrides' /v $1 /d native /f >/dev/null 2>&1
                }

                # Enable DXVK for Direct3D 9/10/11 over Vulkan
                /bin/bash /opt/regataos-wine/dxvk/setup_dxvk.sh install --symlink

                # Enable VKD3D-Proton for Direct3D 12 over Vulkan
                /bin/bash /opt/regataos-wine/vkd3d-proton/setup_vkd3d_proton.sh install --symlink

                # If GPU is NVIDIA, install DXVK-NVAPI
                if test -e /usr/bin/nvidia-xconfig; then
                    ln -sfv /opt/regataos-wine/dxvk-nvapi/x32/*.dll $WINEPREFIX/drive_c/windows/syswow64/
                    ln -sfv /opt/regataos-wine/dxvk-nvapi/x64/*.dll $WINEPREFIX/drive_c/windows/system32/

                    for dll in $(ls /opt/regataos-wine/dxvk-nvapi/x32/ | grep "dll"); do
                        overrideDll $(echo "$dll" | sed s/.dll//)
                    done

                    for dll in $(ls /opt/regataos-wine/dxvk-nvapi/x64/ | grep "dll"); do
                        overrideDll $(echo "$dll" | sed s/.dll//)
                    done

                    echo -e "DXVK\nDXVK-NVAPI\nVKD3D-Proton" >"$WINEPREFIX/vulkan.txt"

                else
                    echo -e "DXVK\nVKD3D-Proton" >"$WINEPREFIX/vulkan.txt"
                fi
            fi
        fi
    fi

    sleep 10
}

case $1 in
"-configure-dxvk-vkd3d")
    configure_dxvk_vkd3d
    ;;
*)
    echo "Invalid option!"
    exit 1
    ;;
esac
