#!/bin/bash
# Script that helps automate the execution of games with Regata OS Game Access

# Game Access configuration file and log file
GCS_CONFIG="$HOME/.config/regataos-gcs/regataos-gcs.conf"
LOG_FILE="/var/log/regataos-logs/steam-$GAME_ID.log"
LOCAL_CONFIG=$HOME/.local/share/Steam/userdata/*/config/localconfig.vdf

# Prepare GL shader disk cache patch for NVIDIA
if test ! -e "$HOME/.local/share/Steam/nvidia-gl-shader-disk-cache-patch"; then
	mkdir -p "$HOME/.local/share/Steam/nvidia-gl-shader-disk-cache-patch"
fi

export NVIDIA_GL_SHADER_DISK_CACHE_PATH="$HOME/.local/share/Steam/nvidia-gl-shader-disk-cache-patch"
export RADV_PERFTEST=gpl

# Gamescope is problematic with these environment variables
if [[ $(cat $LOCAL_CONFIG) != *"gamescope"* ]]; then
	# Enable AMD FSR
	if [[ $(grep -r amd-fsr $GCS_CONFIG) == *"amd-fsr=true"* ]]; then
		export WINE_FULLSCREEN_FSR=1
		export WINE_FULLSCREEN_FSR_STRENGTH=1
	fi

	# Enable performance info
	if [[ $(grep -r fps $GCS_CONFIG) == *"fps=true"* ]]; then
		export MANGOHUD_CONFIG=cpu_temp,cpu_mhz,ram,vram,gpu_core_clock,gpu_temp,gpu_name,benchmark_percentiles,gamemode,font_size=19
		export MANGOHUD=1
		export MANGOHUD_DLSYM=1
		export DXVK_HUD=compiler
	fi
fi

# Check device graphics 
if test -e "/usr/bin/nvidia-xconfig"; then
	# For the NVIDIA proprietary driver
	export __GL_SHADER_DISK_CACHE=1
	export __GL_SHADER_DISK_CACHE_PATH="$NVIDIA_GL_SHADER_DISK_CACHE_PATH"
	export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1

	# If necessary, run software with the NVIDIA dGPU
	if test -e "/tmp/regataos-prime/use-hybrid-graphics.txt"; then
		export GAMEMODERUNEXEC="env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only"
	fi

else
	# If necessary, run software with the AMD/Intel dGPU
	if test -e "/tmp/regataos-prime/use-hybrid-graphics.txt"; then
		export GAMEMODERUNEXEC="env DRI_PRIME=1"
	fi
fi

# Automatically close the Game Access app
/opt/regataos-gcs/scripts/action-games/auto-close-game-access &

# Run game
# Choose suitable option for gamescope and gamemode
(steam steam://rungameid/$GAME_ID) 2>&1 | tee $LOG_FILE

# Clear cache
rm -f "/tmp/regataos-gcs/running-$GAME_NICKNAME"
