#!/bin/bash
# Script that helps automate the execution of games with Regata OS Game Access

# Location of the application's prefix and executable
PREFIX_LOCATION="$HOME/.local/share/wineprefixes/epicstore-compatibility-mode"
GCS_CONFIG="$HOME/.config/regataos-gcs/regataos-gcs.conf"
LOG_FILE="/var/log/regataos-logs/epicstore-$GAMEID.log"

# Capture game executable
file_search="$HOME/.config/legendary/installed.json"
search="$GAMEID"
line_search=$(cat -n $file_search | grep -w $search | head -4 | tail -1 | awk '{print $1}')
search_result=$(
	qt=$(wc -l $file_search | awk '{print $1}')
	sed -n ''$line_search','$qt'p' $file_search
)
executable=$(echo "$search_result" | head -12 | grep executable | cut -d'"' -f 4- | cut -d'"' -f -1)
echo "$executable" >"/tmp/regataos-gcs/game-executable.txt"

# Variables
export WINEPREFIX="$PREFIX_LOCATION"
export WINEESYNC=1
export WINEFSYNC=1
export WINEFSYNC_FUTEX2=1
export WINE_LARGE_ADDRESS_AWARE=1
export DXVK_ASYNC=1
#export DXVK_STATE_CACHE=reset
export DXVK_STATE_CACHE_PATH="$PREFIX_LOCATION"
export DXVK_LOG_PATH="$PREFIX_LOCATION"
export PROTON_BATTLEYE_RUNTIME="/opt/regataos-wine/runtimes-anticheats/battleye_runtime"
export PROTON_EAC_RUNTIME="/opt/regataos-wine/runtimes-anticheats/eac_runtime"

# DXVK-NVAPI
if [[ $(cat "$PREFIX_LOCATION/vulkan.txt") == *"DXVK-NVAPI"* ]]; then
	if [[ $(echo $GAMEID) == *"Heather"* ]]; then
		export WINEDLLOVERRIDES="vulkan-1=n,b;mscoree,mshtml,winemenubuilder,winedbg=";
	else
		export WINEDLLOVERRIDES="mscoree,mshtml,winemenubuilder,winedbg=";
	fi

else
	if [[ $(echo $GAMEID) == *"Heather"* ]]; then
		export WINEDLLOVERRIDES="vulkan-1=n,b;mscoree,mshtml,winemenubuilder,winedbg,nvapi,nvapi64=";
	else
		export WINEDLLOVERRIDES="mscoree,mshtml,winemenubuilder,winedbg,nvapi,nvapi64=";
	fi
fi

# DXVK configuration file
if test -e "$PREFIX_LOCATION/dxvk.conf"; then
	export DXVK_CONFIG_FILE="$PREFIX_LOCATION/dxvk.conf"
fi

# Enable AMD FSR
if [[ $(grep -r amd-fsr $GCS_CONFIG) == *"amd-fsr=true"* ]]; then
	export WINE_FULLSCREEN_FSR=1
	export WINE_FULLSCREEN_FSR_STRENGTH=1
fi

# Enable performance info
if [[ $(grep -r fps $GCS_CONFIG) == *"fps=true"* ]]; then
	export MANGOHUD_CONFIG=cpu_temp,cpu_mhz,ram,vram,gpu_core_clock,gpu_temp,gpu_name,benchmark_percentiles,gamemode,font_size=19
	export MANGOHUD_DLSYM=1
	export MANGOHUD_GL="mangohud --dlsym"
	export DXVK_HUD=compiler
	#export DXVK_HUD=devinfo,fps,frametimes,gpuload,api,compiler
fi

# Check device graphics 
if test -e "/usr/bin/nvidia-xconfig"; then
	# For the NVIDIA proprietary driver
	export __GL_SHADER_DISK_CACHE=1
	export __GL_SHADER_DISK_CACHE_PATH="$PREFIX_LOCATION"
	export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1

	# If necessary, run software with the NVIDIA dGPU
	if test -e "/tmp/regataos-prime/use-hybrid-graphics.txt"; then
		export GAMEMODERUNEXEC="env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only $(echo $MANGOHUD_GL)"
	else
		export GAMEMODERUNEXEC="env $(echo $MANGOHUD_GL)"
	fi

	# Special configurations for DXVK with NVIDIA GPU
	ln -sf "/opt/regataos-wine/custom-configs/epicstore/dxvk-nvidia.conf" "$PREFIX_LOCATION/dxvk.conf"

else
	# If necessary, run software with the AMD/Intel dGPU
	if test -e "/tmp/regataos-prime/use-hybrid-graphics.txt"; then
		export GAMEMODERUNEXEC="env DRI_PRIME=1 $(echo $MANGOHUD_GL)"
	else
		export GAMEMODERUNEXEC="env $(echo $MANGOHUD_GL)"
	fi

	# Special configurations for DXVK with AMD/Intel GPU
	ln -sf "/opt/regataos-wine/custom-configs/epicstore/dxvk.conf" "$PREFIX_LOCATION/dxvk.conf"
fi

# Configure compatibility mode
/bin/bash /opt/regataos-gcs/scripts/action-games/configure-compatibility-mode -configure-dxvk-vkd3d

# Fix for games
cp -f "/opt/regataos-gcs/tools/legendary/config.ini" "$HOME/.config/legendary/config.ini"

# Run game
(/opt/regataos-gcs/tools/legendary/legendary launch "$GAMEID" --wine-prefix "$PREFIX_LOCATION") 2>&1 | tee $LOG_FILE
