#!/bin/sh
# Script that helps automate the execution of games with Regata OS Game Access

# Game Access configuration file and log file
GCS_CONFIG="$HOME/.config/regataos-gcs/regataos-gcs.conf"
LOG_FILE="/var/log/regataos-logs/steam-$GAMEID.log"

# Prepare GL shader disk cache patch for NVIDIA
if test ! -e "$HOME/.local/share/Steam/nvidia-gl-shader-disk-cache-patch"; then
	mkdir -p "$HOME/.local/share/Steam/nvidia-gl-shader-disk-cache-patch"
fi
NVIDIA_GL_SHADER_DISK_CACHE_PATH="$HOME/.local/share/Steam/nvidia-gl-shader-disk-cache-patch"

# Enable performance info
if [[ $(grep -r fps $GCS_CONFIG) == *"fps=true"* ]]; then
	export MANGOHUD_CONFIG=cpu_temp,cpu_mhz,ram,vram,gpu_core_clock,gpu_temp,gpu_name,benchmark_percentiles,gamemode,font_size=19
	export MANGOHUD=1
	export MANGOHUD_GL="mangohud"
	#export DXVK_HUD=devinfo,fps,frametimes,gpuload,api,compiler
fi

# If necessary, run osftware with the dGPU
if test -e /tmp/regataos-prime/use-hybrid-graphics.txt ; then
	if test -e /usr/bin/nvidia-xconfig ; then
		# For the NVIDIA proprietary driver
		export GAMEMODERUNEXEC="env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only __GL_SHADER_DISK_CACHE=1 __GL_SHADER_DISK_CACHE_PATH=$NVIDIA_GL_SHADER_DISK_CACHE_PATH __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1 $(echo $MANGOHUD_GL)"
	else
		# For open source drivers
		export GAMEMODERUNEXEC="env DRI_PRIME=1 $(echo $MANGOHUD_GL)"
	fi

else
	if test -e /usr/bin/nvidia-xconfig ; then
		# For the NVIDIA proprietary driver
		export GAMEMODERUNEXEC="env __GL_SHADER_DISK_CACHE=1 __GL_SHADER_DISK_CACHE_PATH=$NVIDIA_GL_SHADER_DISK_CACHE_PATH __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1 $(echo $MANGOHUD_GL)"
	else
		# For the MangoHud
		export GAMEMODERUNEXEC="env $(echo $MANGOHUD_GL)"
	fi
fi

# Run game
(gamemoderun steam steam://rungameid/$GAMEID) 2>&1 | tee $LOG_FILE
