#!/bin/sh
# Script that helps automate the execution of games with Regata OS Game Access

# Location of the application's prefix and executable
PREFIX_LOCATION="$HOME/.local/share/wineprefixes/$LAUNCHER-compatibility-mode"
GCS_CONFIG="$HOME/.config/regataos-gcs/regataos-gcs.conf"
LOG_FILE="/var/log/regataos-logs/$LAUNCHER-$GAME.log"

if [ -z $RUNGAME ];then
	if [[ $(grep -r "$GAME" "$HOME/.config/regataos-gcs/game-install-dir.conf" | cut -d"=" -f -1) == *"$GAME"* ]]; then
		export GAME_EXEC=$(grep -r "$GAME=" "$HOME/.config/regataos-gcs/game-install-dir.conf" | cut -d"=" -f 2-)
	else
		/opt/regataos-wine/apps-exec/$LAUNCHER start
		exit 0
	fi
fi

# Variables for custom Wine
CUSTOM_WINE_DIR="/opt/regataos-wine/wine-fshack"
WINESERVER=$CUSTOM_WINE_DIR/bin/wineserver
WINELOADER=$CUSTOM_WINE_DIR/bin/wine
WINEDLLPATH=$CUSTOM_WINE_DIR/lib:$CUSTOM_WINE_DIR/lib64

# Variables
export WINEPREFIX="$PREFIX_LOCATION"
export WINEDLLOVERRIDES="winemenubuilder,winedbg,nvapi,nvapi64="
export DXVK_STATE_CACHE_PATH="$PREFIX_LOCATION"
export DXVK_LOG_PATH="$PREFIX_LOCATION"

if test -e "$PREFIX_LOCATION/dxvk.conf"; then
	export DXVK_CONFIG_FILE="$PREFIX_LOCATION/dxvk.conf"
fi

# Enable performance info
if [[ $(grep -r fps $GCS_CONFIG) == *"fps=true"* ]]; then
	export MANGOHUD_CONFIG=cpu_temp,cpu_mhz,ram,vram,gpu_core_clock,gpu_temp,gpu_name,benchmark_percentiles,gamemode,font_size=19
	export MANGOHUD=1
	export MANGOHUD_GL="mangohud"
	#export DXVK_HUD=devinfo,fps,frametimes,gpuload,api,compiler
fi

# If necessary, run osftware with the dGPU
if test -e /tmp/regataos-prime/use-hybrid-graphics.txt ; then
	if test -e /usr/bin/nvidia-xconfig ; then
		# For the NVIDIA proprietary driver
		export GAMEMODERUNEXEC="env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only __GL_SHADER_DISK_CACHE=1 __GL_SHADER_DISK_CACHE_PATH=$PREFIX_LOCATION __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1 $(echo $MANGOHUD_GL)"

		# Special configurations for DXVK with NVIDIA GPU
		ln -sf "/opt/regataos-wine/custom-configs/$LAUNCHER/dxvk-nvidia.conf" "$PREFIX_LOCATION/dxvk.conf"
	else
		# For open source drivers
		export GAMEMODERUNEXEC="env DRI_PRIME=1 $(echo $MANGOHUD_GL)"

		# Special configurations for DXVK with AMD/Intel GPU
		ln -sf "/opt/regataos-wine/custom-configs/$LAUNCHER/dxvk.conf" "$PREFIX_LOCATION/dxvk.conf"
	fi

else
	if test -e /usr/bin/nvidia-xconfig ; then
		# For the NVIDIA proprietary driver
		export GAMEMODERUNEXEC="env __GL_SHADER_DISK_CACHE=1 __GL_SHADER_DISK_CACHE_PATH=$PREFIX_LOCATION __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1 $(echo $MANGOHUD_GL)"

		# Special configurations for DXVK with NVIDIA GPU
		ln -sf "/opt/regataos-wine/custom-configs/$LAUNCHER/dxvk-nvidia.conf" "$PREFIX_LOCATION/dxvk.conf"

	else
		# For the MangoHud
		export GAMEMODERUNEXEC="env $(echo $MANGOHUD_GL)"

		# Special configurations for DXVK with AMD/Intel GPU
		ln -sf "/opt/regataos-wine/custom-configs/$LAUNCHER/dxvk.conf" "$PREFIX_LOCATION/dxvk.conf"
	fi
fi

# Run game
if [ -z $RUNGAME ];then
	(env $GAMEVAR gamemoderun $CUSTOM_WINE_DIR/bin/wine "$GAME_EXEC") 2>&1 | tee $LOG_FILE
else
	(env $GAMEVAR gamemoderun $CUSTOM_WINE_DIR/bin/wine start "$RUNGAME") 2>&1 | tee $LOG_FILE
fi
