#!/bin/sh
# Script that helps automate the execution of games with Regata OS Game Access

# Location of the application's prefix and executable
PREFIX_LOCATION="$HOME/.local/share/wineprefixes/gog-compatibility-mode"
GCS_CONFIG="$HOME/.config/regataos-gcs/regataos-gcs.conf"
LOG_FILE="/var/log/regataos-logs/gog-$GAME_NIcKNAME.log"

# Capture game info
game_install_folder=$(grep -r "$GAME_NIcKNAME" "$HOME/.config/regataos-gcs/gog-games/games-folders2.txt" | cut -d':' -f 2- | sed 's/ //')
gameid=$(grep -r "gameId" "$game_install_folder"/goggame-*.info | awk '{print $2}' | sed 's/"\|,//g')

# Variables for custom Wine
export CUSTOM_WINE_DIR="$(cat /opt/regataos-wine/wine-gcs-version.txt)"
export WINESERVER=$CUSTOM_WINE_DIR/bin/wineserver
export WINELOADER=$CUSTOM_WINE_DIR/bin/wine
export WINEDLLPATH=$CUSTOM_WINE_DIR/lib:$CUSTOM_WINE_DIR/lib64
export WINE="$CUSTOM_WINE_DIR/bin/wine"

# Try specifying the wine-mono and wine-gecko directory
export WINE_MONO_CACHE_DIR="$CUSTOM_WINE_DIR/mono"
export WINE_GECKO_CACHE_DIR="$CUSTOM_WINE_DIR/gecko"

# Variables
export WINEPREFIX="$PREFIX_LOCATION"
export WINEDLLOVERRIDES="mscoree,mshtml,winemenubuilder,winedbg="
export WINEESYNC=1
export WINEFSYNC=1
export WINEFSYNC_FUTEX2=1
export WINE_LARGE_ADDRESS_AWARE=1
export DXVK_STATE_CACHE_PATH="$PREFIX_LOCATION"
export DXVK_LOG_PATH="$PREFIX_LOCATION"

# Enable AMD FSR
if [[ $(grep -r amd-fsr $GCS_CONFIG) == *"amd-fsr=true"* ]]; then
	export WINE_FULLSCREEN_FSR=1
	export WINE_FULLSCREEN_FSR_STRENGTH=2
fi

# Enable performance info
if [[ $(grep -r fps $GCS_CONFIG) == *"fps=true"* ]]; then
	export MANGOHUD_CONFIG=cpu_temp,cpu_mhz,ram,vram,gpu_core_clock,gpu_temp,gpu_name,benchmark_percentiles,gamemode,font_size=19
	export MANGOHUD_DLSYM=1
	export MANGOHUD_GL="mangohud --dlsym"
	#export DXVK_HUD=devinfo,fps,frametimes,gpuload,api,compiler
fi

# If necessary, run osftware with the dGPU
if test -e /tmp/regataos-prime/use-hybrid-graphics.txt ; then
	if test -e /usr/bin/nvidia-xconfig ; then
		# For the NVIDIA proprietary driver
		export GAMEMODERUNEXEC="env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only __GL_SHADER_DISK_CACHE=1 __GL_SHADER_DISK_CACHE_PATH=$PREFIX_LOCATION __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1 $(echo $MANGOHUD_GL)"

		# Special configurations for DXVK with NVIDIA GPU
		ln -sf "/opt/regataos-wine/custom-configs/$LAUNCHER/dxvk-nvidia.conf" "$PREFIX_LOCATION/dxvk.conf"
	else
		# For open source drivers
		export GAMEMODERUNEXEC="env DRI_PRIME=1 $(echo $MANGOHUD_GL)"

		# Special configurations for DXVK with AMD/Intel GPU
		ln -sf "/opt/regataos-wine/custom-configs/$LAUNCHER/dxvk.conf" "$PREFIX_LOCATION/dxvk.conf"
	fi

else
	if test -e /usr/bin/nvidia-xconfig ; then
		# For the NVIDIA proprietary driver
		export GAMEMODERUNEXEC="env __GL_SHADER_DISK_CACHE=1 __GL_SHADER_DISK_CACHE_PATH=$PREFIX_LOCATION __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1 $(echo $MANGOHUD_GL)"

		# Special configurations for DXVK with NVIDIA GPU
		ln -sf "/opt/regataos-wine/custom-configs/$LAUNCHER/dxvk-nvidia.conf" "$PREFIX_LOCATION/dxvk.conf"

	else
		# For the MangoHud
		export GAMEMODERUNEXEC="env $(echo $MANGOHUD_GL)"

		# Special configurations for DXVK with AMD/Intel GPU
		ln -sf "/opt/regataos-wine/custom-configs/$LAUNCHER/dxvk.conf" "$PREFIX_LOCATION/dxvk.conf"
	fi
fi

# DXVK configuration file
if test -e "$PREFIX_LOCATION/dxvk.conf"; then
	export DXVK_CONFIG_FILE="$PREFIX_LOCATION/dxvk.conf"
fi

# Run game
(env $GAMEVAR gamemoderun $CUSTOM_WINE_DIR/bin/wine "$PREFIX_LOCATION/dosdevices/c:/Program Files (x86)/GOG Galaxy/GalaxyClient.exe" /command=runGame /gameId=$gameid /path="$game_install_folder") 2>&1 | tee $LOG_FILE
