#!/bin/bash
# Script that helps automate the execution of games with Regata OS Game Access

# Location of the application's prefix and executable
PREFIX_LOCATION="$HOME/.local/share/wineprefixes/$LAUNCHER-compatibility-mode"
LOG_FILE="/var/log/regataos-logs/$LAUNCHER.log"

# Variables
export WINEPREFIX="$PREFIX_LOCATION"
export DXVK_LOG_PATH="$PREFIX_LOCATION"
export WINEDLLOVERRIDES="mscoree,mshtml,winemenubuilder="

# Run launcher
(wine "$RUN_EXE") 2>&1 | tee $LOG_FILE
