#!/bin/bash
# Script that helps automate the execution of games with Regata OS Game Access

# Location of the application's prefix and executable
PREFIX_LOCATION="$HOME/.local/share/wineprefixes/$LAUNCHER-compatibility-mode"
LOG_FILE="/var/log/regataos-logs/$LAUNCHER-external-executable.log"

# Variables
export WINEPREFIX="$PREFIX_LOCATION"
export WINEDLLOVERRIDES="winemenubuilder="
export DXVK_LOG_PATH="$PREFIX_LOCATION"
export DXVK_STATE_CACHE_PATH="$PREFIX_LOCATION"
export PROTON_BATTLEYE_RUNTIME="/opt/regataos-wine/runtimes-anticheats/battleye_runtime"
export PROTON_EAC_RUNTIME="/opt/regataos-wine/runtimes-anticheats/eac_runtime"

# Run launcher
(wine "$RUN_EXE") 2>&1 | tee $LOG_FILE

echo "Running: $RUN_EXE" >> $LOG_FILE
