#!/bin/bash

# Try to find the gameId
function forGameId() {
	search_dir="$HOME/.local/share/wineprefixes/gog-compatibility-mode/drive_c/ProgramData/GOG.com/Galaxy/webcache/"
	search_gameid=$(echo "$for_id" | sed 's/\// /g' | cut -d'?' -f -1 | awk '{print $3}')
	game_id=$(find "$search_dir" -type f -iname "$search_gameid" | sed 's/\// /g' | awk '{print $14}' | head -1)
}

# Create JSON files in game cache on GOG Galaxy account
function create_gog_cache() {
forGameId

mkdir -p "/tmp/regataos-gcs/config/gog-games/json/"
cat > "/tmp/regataos-gcs/config/gog-games/json/$gamename_lowercase-gog.json" << GOGGAMEJSONCACHE
[
	{
		"gamename": "$game_name",
		"gamenickname": "$gamename_lowercase",
		"gameid": "$game_id",
		"gameid": "$gamename_lowercase",
		"gamekeywords": "$game_name, $gamekeywords, gog galaxy",
		"launcher": "GOG Galaxy",
		"launchernickname": "gog",
		"gameinstallfolder": "$gameinstallfolder"
    }
]
GOGGAMEJSONCACHE
}

# Update JSON files in game cache
function update_games_cache() {
forGameId

cat > "/opt/regataos-gcs/games-list/$gamename_lowercase-gog.json" << GOGGAMEJSON
[
	{
		"gamename": "$game_name",
		"gamenickname": "$gamename_lowercase",
		"gameid": "$game_id",
		"gamekeywords": "$game_name, $gamekeywords, gog galaxy",
		"launcher": "GOG Galaxy",
		"launchernickname": "gog",
		"gameinstallfolder": "$gameinstallfolder"
    }
]
GOGGAMEJSON
}

case $1 in
   "-create-gog-cache") create_gog_cache
         ;;
   "-up-games-cache") update_games_cache
         ;;
   *) echo "Invalid option!"
      exit 1
      ;;
esac
