#!/bin/bash

# Create JSON files in game cache on Steam account

#Create JSON file
if test ! -e "/tmp/regataos-gcs/config/steam-games/json/games-account/$gameid.json"; then
cat > "/tmp/regataos-gcs/config/steam-games/json/games-account/$gameid.json" << STEAMGAMEJSON
[
	{
		"gamename": "$gamename",
		"gameid": "$gameid",
		"gametype": "$gametype",
		"gamenative": "$gamenative"
    }
]
STEAMGAMEJSON
fi

#Save game image to cache
if test ! -e "/tmp/regataos-gcs/config/steam-games/img/$gameid.jpg"; then
	wget --no-check-certificate -O "/tmp/regataos-gcs/config/steam-games/img/$gameid.jpg" "https://cdn.cloudflare.steamstatic.com/steam/apps/$gameid/header.jpg"
fi
