#!/bin/bash
#
# A simple script to extract the compatibility tool files for Game Access
tar xf "$1" -C "$2"

# Check DXVK and VKD3D-Proton installation scripts
if test ! -e "/opt/regataos-wine/dxvk/setup_dxvk.sh"; then
	cp -fv "/opt/regataos-wine/setup_dxvk.sh" "/opt/regataos-wine/dxvk/setup_dxvk.sh"
fi

if test ! -e "/opt/regataos-wine/vkd3d-proton/setup_vkd3d-proton.sh"; then
	cp -fv "/opt/regataos-wine/setup_vkd3d-proton.sh" "/opt/regataos-wine/vkd3d-proton/setup_vkd3d-proton.sh"
fi
