#!/bin/bash

cd /

while :
do

# Check if the Regata OS Game Access is running
ps -C "regataosgcs /opt/regataos-gcs" > /dev/null
if [ $? = 0 ]
then
	# Search for installed games
	/bin/bash /opt/regataos-gcs/scripts/search-installed-games.sh & /bin/bash /opt/regataos-gcs/scripts/search-steam-games.sh
else
	echo "Nothing to do..."
	break
fi

   sleep 5
done
