#!/bin/bash

# Search for installed games
function search_installeds() {
	sleep 5

	/bin/bash /opt/regataos-gcs/scripts/search-installed-games.sh & \
	/bin/bash /opt/regataos-gcs/scripts/search-steam-games.sh & \
	/bin/bash /opt/regataos-gcs/scripts/search-gog-games.sh & \
	/bin/bash /opt/regataos-gcs/scripts/search-installed-games-gog.sh & \
	/bin/bash /opt/regataos-gcs/scripts/search-epicstore-games.sh &

	# Capture the games installation folder from the Epic Games Store
	if test -e "/tmp/progressbar-gcs/download-percentage-legendary"; then
		if test ! -e "/tmp/regataos-gcs/game-patch-epicstore.txt"; then
			if [[ $(grep -r "Install path" "/tmp/progressbar-gcs/download-percentage-legendary") == *"Install path"* ]]; then
				install_path="$(grep -r "Install path" "/tmp/progressbar-gcs/download-percentage-legendary" | cut -d":" -f 3- | cut -d" " -f 2-)"
				echo "$install_path" > "/tmp/regataos-gcs/game-patch-epicstore.txt"
			fi
		fi
	fi
}

# Check for JSON files in the directory listing installed games
function detect_games() {
	directory_installed_json="/tmp/regataos-gcs/config/installed"
	check_installed_games=$(ls $directory_installed_json/)

	if [[ $(echo $check_installed_games) == *".json"* ]]; then
		echo "Show installed games" > "$directory_installed_json/show-installed-games.txt"

		if [[ $(echo $check_installed_games) == *"epicstore.json"* ]]; then
			if test ! -e "$directory_installed_json/show-installed-games-epic.txt"; then
				echo "show EGS installed" > "$directory_installed_json/show-installed-games-epic.txt"
			fi
		else
			rm -f "$directory_installed_json/show-installed-games-epic.txt"
		fi
	else 
		rm -f "$directory_installed_json/show-installed-games.txt"
	fi
}

case $1 in
   "-search") detect_games && search_installeds
        ;;
   "--detect") detect_games
        ;;
   *) echo "Invalid option!"
      exit 1
      ;;
esac
