#!/bin/bash

cd /

while :
do

# Fix for progressbar-gcs folder
user=$(users | awk '{print $1}')
if test ! -e "/tmp/progressbar-gcs" ; then
	if test -e "/home/$user/.config/regataos-gcs/progressbar-gcs" ; then
		ln -sf "/home/$user/.config/regataos-gcs/progressbar-gcs" "/tmp/progressbar-gcs"
	fi
else
	if test ! -e "/tmp/progressbar-gcs/installing" ; then
		rm -f /tmp/progressbar-gcs/*
	fi
fi

# Select language
function lang_clear_cache() {
	# Clear cache
	rm -rf "/opt/regataos-gcs/scripts/install/scripts-install"
	rm -rf "/opt/regataos-gcs/scripts/remove/scripts-remove"
	rm -rf "/opt/regataos-gcs/www/js/translations/language"
}

function lang_pt_BR() {
	ln -sf /opt/regataos-gcs/scripts/install/pt-br /opt/regataos-gcs/scripts/install/scripts-install
	ln -sf /opt/regataos-gcs/scripts/remove/pt-br /opt/regataos-gcs/scripts/remove/scripts-remove
	ln -sf /opt/regataos-gcs/www/js/translations/pt-br /opt/regataos-gcs/www/js/translations/language
}

function lang_pt_PT() {
	ln -sf /opt/regataos-gcs/scripts/install/pt-br /opt/regataos-gcs/scripts/install/scripts-install
	ln -sf /opt/regataos-gcs/scripts/remove/pt-br /opt/regataos-gcs/scripts/remove/scripts-remove
	ln -sf /opt/regataos-gcs/www/js/translations/pt-br /opt/regataos-gcs/www/js/translations/language
}

function lang_en_US() {
	ln -sf /opt/regataos-gcs/scripts/install/en-us /opt/regataos-gcs/scripts/install/scripts-install
	ln -sf /opt/regataos-gcs/scripts/remove/en-us /opt/regataos-gcs/scripts/remove/scripts-remove
	ln -sf /opt/regataos-gcs/www/js/translations/en-us /opt/regataos-gcs/www/js/translations/language
}

user=$(users | awk '{print $1}')
if test -e "/home/$user/.config/plasma-localerc" ; then
	lang=$(grep -r LANG "/home/$user/.config/plasma-localerc")

	if [[ $lang == *"pt_BR"* ]]; then
		lang_clear_cache
		lang_pt_BR

	elif [[ $lang == *"pt_PT"* ]]; then
		lang_clear_cache
		lang_pt_PT

	elif [[ $lang == *"en_US"* ]]; then
		lang_clear_cache
		lang_en_US

	else
		lang_clear_cache
		lang_en_US
	fi

	break
else
	if test -e "/home/$user/.config/user-dirs.locale" ; then
		lang=$(cat "/home/$user/.config/user-dirs.locale")

		if [[ $lang == *"pt_BR"* ]]; then
			lang_clear_cache
			lang_pt_BR

		elif [[ $lang == *"pt_PT"* ]]; then
			lang_clear_cache
			lang_pt_PT

		elif [[ $lang == *"en_US"* ]]; then
			lang_clear_cache
			lang_en_US

		else
			lang_clear_cache
			lang_en_US
		fi

		break
	fi
fi

   sleep 1
done
