#!/bin/bash

# Enable/desable FPS
function fps_hud() {
    if [[ $(grep -r fps "$HOME/.config/regataos-gcs/regataos-gcs.conf") == *"fps=true"* ]]; then
        sed -i 's/\(fps=true\)/fps=false/' "$HOME/.config/regataos-gcs/regataos-gcs.conf"

    elif [[ $(grep -r fps "$HOME/.config/regataos-gcs/regataos-gcs.conf") == *"fps=false"* ]]; then
        sed -i 's/\(fps=false\)/fps=true/' "$HOME/.config/regataos-gcs/regataos-gcs.conf"

    else
        echo "fps=true" >> "$HOME/.config/regataos-gcs/regataos-gcs.conf"
        sed -i '/^$/d' "$HOME/.config/regataos-gcs/regataos-gcs.conf"
    fi
}

# Enable/disable automatic closing of Game Access
function auto_close() {
    if [[ $(grep -r auto-close "$HOME/.config/regataos-gcs/regataos-gcs.conf") == *"auto-close=true"* ]]; then
        sed -i 's/\(auto-close=true\)/auto-close=false/' "$HOME/.config/regataos-gcs/regataos-gcs.conf"

    elif [[ $(grep -r auto-close "$HOME/.config/regataos-gcs/regataos-gcs.conf") == *"auto-close=false"* ]]; then
        sed -i 's/\(auto-close=false\)/auto-close=true/' "$HOME/.config/regataos-gcs/regataos-gcs.conf"

    else
        echo "auto-close=true" >> "$HOME/.config/regataos-gcs/regataos-gcs.conf"
        sed -i '/^$/d' "$HOME/.config/regataos-gcs/regataos-gcs.conf"
    fi
}

case $1 in
   "-fpshud") fps_hud
         ;;
   "-autoclose") auto_close
         ;;
   *) echo "Invalid option!"
      exit 1
      ;;
esac
