#!/bin/bash

# Enable/desable FPS
function fps_hud() {
    if [[ $(grep -r fps "$HOME/.config/regataos-gcs/regataos-gcs.conf") == *"fps=true"* ]]; then
        sed -i 's/\(fps=true\)/fps=false/' "$HOME/.config/regataos-gcs/regataos-gcs.conf"

    elif [[ $(grep -r fps "$HOME/.config/regataos-gcs/regataos-gcs.conf") == *"fps=false"* ]]; then
        sed -i 's/\(fps=false\)/fps=true/' "$HOME/.config/regataos-gcs/regataos-gcs.conf"

    else
        echo "fps=true" >> "$HOME/.config/regataos-gcs/regataos-gcs.conf"
        sed -i '/^$/d' "$HOME/.config/regataos-gcs/regataos-gcs.conf"
    fi
}

# Enable/disable automatic closing of Game Access
function auto_close() {
    if [[ $(grep -r auto-close "$HOME/.config/regataos-gcs/regataos-gcs.conf") == *"auto-close=true"* ]]; then
        sed -i 's/\(auto-close=true\)/auto-close=false/' "$HOME/.config/regataos-gcs/regataos-gcs.conf"

    elif [[ $(grep -r auto-close "$HOME/.config/regataos-gcs/regataos-gcs.conf") == *"auto-close=false"* ]]; then
        sed -i 's/\(auto-close=false\)/auto-close=true/' "$HOME/.config/regataos-gcs/regataos-gcs.conf"

    else
        echo "auto-close=true" >> "$HOME/.config/regataos-gcs/regataos-gcs.conf"
        sed -i '/^$/d' "$HOME/.config/regataos-gcs/regataos-gcs.conf"
    fi
}

# Enable/desable AMD FSR
function amd_fsr() {
    if [[ $(grep -r amd-fsr "$HOME/.config/regataos-gcs/regataos-gcs.conf") == *"amd-fsr=true"* ]]; then
        sed -i 's/\(amd-fsr=true\)/amd-fsr=false/' "$HOME/.config/regataos-gcs/regataos-gcs.conf"

    elif [[ $(grep -r amd-fsr "$HOME/.config/regataos-gcs/regataos-gcs.conf") == *"amd-fsr=false"* ]]; then
        sed -i 's/\(amd-fsr=false\)/amd-fsr=true/' "$HOME/.config/regataos-gcs/regataos-gcs.conf"

    else
        /opt/regataos-gcs/scripts/check-support-amd-fsr.sh start
        sed -i '/^$/d' "$HOME/.config/regataos-gcs/regataos-gcs.conf"
    fi
}

case $1 in
   "-fpshud") fps_hud
         ;;
   "-autoclose") auto_close
         ;;
   "-amd-fsr") amd_fsr
         ;;
   *) echo "Invalid option!"
      exit 1
      ;;
esac
