#!/bin/bash

# Download the script that updates the home content
if test ! -e "$HOME/.config/regataos-gcs/cache"; then
	mkdir -p "$HOME/.config/regataos-gcs/cache/"
fi

wget --no-check-certificate -O "$HOME/.config/regataos-gcs/cache/update-cache-from-home.sh" \
	"https://regataos.github.io/game-access/update-cache-from-home.sh"

chmod +x "$HOME/.config/regataos-gcs/cache/update-cache-from-home.sh"
$HOME/.config/regataos-gcs/cache/update-cache-from-home.sh start
