#!/bin/bash

# Download the script that updates the home content
cache_download_dir="$HOME/.config/regataos-gcs/cache"
download_link="https://regataos.github.io/game-access/update-cache-from-home.sh"

if test ! -e "$cache_download_dir" ; then
	mkdir -p "$cache_download_dir/"
fi

wget --no-check-certificate -O "$cache_download_dir/update-cache-from-home.sh" "$download_link"

chmod +x $cache_download_dir/update-cache-from-home.sh
$cache_download_dir/update-cache-from-home.sh start
