#!/bin/bash

# Detect system language.
user=$(users | awk '{print $1}')

if test -e "/home/$user/.config/plasma-localerc" ; then
	language=$(grep -r LANGUAGE= "/home/$user/.config/plasma-localerc" | cut -d"=" -f 2- | cut -d":" -f -1 | tr [A-Z] [a-z] | sed 's/_/-/')

	if [ -z $language ]; then
    	language=$(grep -r LANG= "/home/$user/.config/plasma-localerc" | cut -d"=" -f 2- | cut -d"." -f -1 | tr [A-Z] [a-z] | sed 's/_/-/')
	fi

elif test -e "/home/$user/.config/user-dirs.locale" ; then
    language=$(cat "/home/$user/.config/user-dirs.locale" | tr [A-Z] [a-z] | sed 's/_/-/')

else
    language=$(echo $LANG | tr [A-Z] [a-z] | sed 's/_/-/' | cut -d"." -f -1)
fi

# Choose the translation of the icon in the system
# tray according to the user's language.
function default_translation_buttons() {
    if [[ $language == *"pt-br"* ]]; then
        yesButton="Sim"
        cancelButton="Cancelar"

    elif [[ $language == *"pt-pt"* ]]; then
        yesButton="Sim"
        cancelButton="Cancelar"

    elif [[ $language == *"pt"* ]]; then
        yesButton="Sim"
        cancelButton="Cancelar"

    elif [[ $language == *"en-us"* ]]; then
        yesButton="Yes"
        cancelButton="Cancel"

    else
        yesButton="Yes"
        cancelButton="Cancel"
    fi
}

# Show/hide the Game Access window, keeping the icon in the system tray.
function show_hide_gcs_window() {
    ps -C "regataosgcs" > /dev/null
    if [ $? = 1 ]; then
        cd /usr/share/applications/; gtk-launch "regataos-gcs.desktop"

    else
        # Keep icon in system tray
        echo "keep icontray" > "/tmp/regataos-gcs/icontray.txt"

        # Close Game Access app
        kill -SIGTERM $(ps -C regataosgcs | head -2 | tail -1 | awk '{print $1}')
    fi
}

# Completely close the Game Access app.
#Translation for exit confirmation window.
function close_app_lang() {
    if [[ $language == *"pt-br"* ]]; then
        title="Fechar o Game Access"
        description="Realmente fechar o Game Access?"
        yesButton="Sim, fechar!"
        cancelButton="Cancelar"

    elif [[ $language == *"pt-pt"* ]]; then
        title="Fechar o Game Access"
        description="Realmente fechar o Game Access?"
        yesButton="Sim, fechar!"
        cancelButton="Cancelar"

    elif [[ $language == *"pt"* ]]; then
        title="Fechar o Game Access"
        description="Realmente fechar o Game Access?"
        yesButton="Sim, fechar!"
        cancelButton="Cancelar"

    elif [[ $language == *"en-us"* ]]; then
        title="Close Game Access"
        description="Really close Game Access?"
        yesButton="Yes, close!"
        cancelButton="Cancel"

    else
        title="Close Game Access"
        description="Really close Game Access?"
        yesButton="Yes, close!"
        cancelButton="Cancel"
    fi
}

#Close the Regata OS Game Access application.
function close_app() {
    kill -SIGTERM $(ps -C regataosgcs | head -2 | tail -1 | awk '{print $1}')
    killall gcs-icontray.py
}

#Before removing the system tray icon, make sure you have any launchers or games running.
function close_gcs_app() {
    confirmExit=""

    # Get the running game executable.
    if test -e "/tmp/regataos-gcs/game-executable.txt"; then
        game_executable=$(cat "/tmp/regataos-gcs/game-executable.txt")
    fi

    # Processes to be verified.
    if [ ! -z $game_executable ];then
        game_process="rungame | rungame-epicstore | rungame-gcs | rungame-gog | rungame-steam | runlauncher | $game_executable"
    else
        game_process="rungame | rungame-epicstore | rungame-gcs | rungame-gog | rungame-steam | runlauncher"
    fi

    ps -C "$game_process" > /dev/null
    if [ $? = 0 ]; then
        confirmExit="yes"

    else
        launchers_process="battlenet | epicstore | gog | origin | eadesktop | rockstar | ubisoftconnect"
        ps -C "$launchers_process" > /dev/null
        if [ $? = 0 ]; then
            confirmExit="yes"
        fi
    fi

    # If any launcher or game is running, confirm Game Access exit.
    if [[ $confirmExit == *"yes"* ]]; then
        if [ -z $yesButton ] || [ -z $cancelButton ];then
            default_translation_buttons
            $TRANSLATIONS

        else
            $TRANSLATIONS
        fi

        env GTK_THEME=Adwaita:dark zenity --question --title "$title" --text "$description" --icon-name=regataos-gcs \
        --ok-label "$yesButton" --cancel-label "$cancelButton" --width 300 --window-icon "/usr/share/pixmaps/regataos-gcs.png"

        if [ $? -eq "0" ]; then
            $FUNCTION
            sleep 1
            exit 0

        else
            echo "Process canceled"
            exit 0
        fi

    else
        $FUNCTION
    fi
}

# Run options.
case $1 in
    "-show-hide-gcs") show_hide_gcs_window
      ;;
    "-close-gcs-app") export FUNCTION="close_app"; export TRANSLATIONS="$(echo $FUNCTION)_lang"; close_gcs_app
      ;;
   *) echo "Invalid option!"
      exit 1
      ;;
esac
